# Generated by Django 4.2.5 on 2023-09-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_boss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boss',
            old_name='files',
            new_name='img',
        ),
    ]
